routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('root');

Auth::routes();

Route::get('/home/{user?}', 'HomeController@index')->name('home');

Route::resource('user','UserController');
Route::resource('assessmentModel','AssessmentModelController');
Route::resource('assessmentCategory','AssessmentCategoryController');
Route::resource('assessmentSubCategory','AssessmentSubCategoryController');
Route::resource('assessmentVariable','AssessmentVariableController');
Route::resource('assessmentVariableValue','AssessmentVariableValueController');
Route::resource('assessmentBenefit','AssessmentBenefitController');

Route::resource('assessmentVariable', 'AssessmentVariableController');
Route::resource('assessmentSubmission', 'AssessmentSubmissionController');

Route::get('/assessmentDump/{assessmentSubmission}', 'AssessmentSubmissionController@dump');

Route::get('methodology/{assessmentModel}','AssessmentModelController@hierarchy')->name('methodology');

Route::get('/submit/{assessmentSubmission}/{assessmentSubCategory}/','AssessmentSubmissionController@submit')->name('submit');
Route::get('/submitBenefits/{assessmentSubmission}','AssessmentSubmissionController@submitBenefits')->name('submitBenefits');

app/AssessmentCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Closure;

class AssessmentCategory extends Model
{
    protected $fillable = [
        'name',
        'description',
        'image',
        'assessment_model_id',
        'display_weight',
    ];

    public function assessmentModel()
    {
        return $this->belongsTo(AssessmentModel::class);
    }

    public function assessmentSubCategories()
    {
        return $this->hasMany(AssessmentSubCategory::class);
    }

    public static function importFromCSV($source_file, Closure $callback)
    {
        if (!file_exists($source_file)) {
            throw new \Exception("File not found: " . $source_file);
        }

        $row_num = 0;
        $headers = [];
        if (($handle = fopen($source_file, "r")) !== FALSE) {
            while (($row = fgetcsv($handle, 4096, ",")) !== FALSE) {
                $row_num++;
                if ($row_num == 1) {
                    $headers = $row;
                    continue;
                }

                $data = [];
                foreach ($row as $k => $v) {
                    $data[$headers[$k]] = $v;
                }

                try {
                    $assessmentModel = assessmentModel::where('name', $data['model'])->first();
                    unset($data['model']);

                    $newRow = $assessmentModel->assessmentCategories()->create($data);
                } catch (\Exception $ex) {
                    print "Shit: Died at " . print_r($data, TRUE);
                    throw $ex;
                }

                $callback($newRow);
            }

            fclose($handle);

            // Account for the header
            return ($row_num - 1);
        }
    }
}

app/Http/Controllers/AssessmentCategoryController.php
<?php

namespace App\Http\Controllers;

use App\AssessmentCategory;
use App\AssessmentModel;
use Illuminate\Foundation\Testing\HttpException;
use Illuminate\Http\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class AssessmentCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $models = AssessmentCategory::simplePaginate();
        return view('assessmentCategory.index', compact('models'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if(! $request->get('parent')){
            throw new NotFoundHttpException("Model not found");
        }

        $parent = AssessmentModel::findOrFail($request->get('parent'));

        return view('assessmentCategory.create', compact('parent'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'description' => 'required',
            'display_weight' => 'required',
            'assessment_model_id' => 'required|exists:assessment_models,id'
        ]);

        $data = $request->all();

        $model = AssessmentCategory::create( $data);

        return redirect(route('assessmentCategory.show', [ $model->id ]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\AssessmentCategory  $assessmentCategory
     * @return \Illuminate\Http\Response
     */
    public function show(AssessmentCategory $assessmentCategory)
    {
        $model = $assessmentCategory;
        return view('assessmentCategory.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\AssessmentCategory  $assessmentCategory
     * @return \Illuminate\Http\Response
     */
    public function edit(AssessmentCategory $assessmentCategory)
    {
        $model = $assessmentCategory;
        return view('assessmentCategory.edit',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AssessmentCategory  $assessmentCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AssessmentCategory $assessmentCategory)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'display_weight' => 'required',
            'description' => 'required',
        ]);

        $assessmentCategory->fill($request->all());
        $assessmentCategory->save();

        return redirect(route('assessmentCategory.show', [ $assessmentCategory->id ]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AssessmentCategory  $assessmentCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy(AssessmentCategory $assessmentCategory)
    {
        //
    }
}

resources/views/assessmentCategory/_form.blade.php
@if($model->id)
    {!! Form::model($model, ['route' => ['assessmentCategory.update', $model->id], 'method' => 'put']) !!}
@else
    {!! Form::model($model, ['route' => ['assessmentCategory.store']]) !!}
@endif

<div class="form-group {{ $errors->has('name') ? 'has-error' :'' }}">
    {{ Form::label('name') }}
    {{ Form::text('name', $model->name, ['class' => "form-control"]) }}
    {!! $errors->first('name','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('description') ? 'has-error' :'' }}">
    {{ Form::label('description') }}
    {{ Form::text('description', $model->description, ['class' => "form-control"]) }}
    {!! $errors->first('description','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('image') ? 'has-error' :'' }}">
    {{ Form::label('image') }}
    {{ Form::text('image', $model->image, ['class' => "form-control"]) }}
    {!! $errors->first('image','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('display_weight') ? 'has-error' :'' }}">
    {{ Form::label('display_weight') }}
    {{ Form::number('display_weight', $model->display_weight, ['class' => "form-control"]) }}
    {!! $errors->first('display_weight','<span class="help-block">:message</span>') !!}
</div>

@if(! $model->id)
    {{Form::hidden('assessment_model_id', $parent->id)}}
@endif

<div class="form-group">
    {{ Form::submit('Save',['class' => 'btn btn-default']) }}
</div>

{!! Form::close() !!}

resources/views/assessmentCategory/create.blade.php
@extends('layouts.app')

@section('page-title', 'Create Category')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentModel.index','Models') }}</li>
        <li class="active">{{ link_to_route('assessmentModel.show', $parent->name, [$parent->id]) }}</li>
        <li>Create Category</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create Category</h3>
                        @include('assessmentCategory._form', [ 'model' => new App\AssessmentCategory() ])
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assessmentCategory/edit.blade.php
@extends('layouts.app')

@section('page-title', 'Update Category')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentModel.index','Models') }}</li>
        <li class="active">{{ link_to_route('assessmentModel.show', $model->assessmentModel->name, [$model->assessmentModel->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentCategory.show', $model->name, [$model->id]) }}</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @include('assessmentCategory._form', compact('assessmentCategory'))
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assessmentCategory/index.blade.php
@extends('layouts.app')

@section('page-title', 'Categories')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentCategory.index','Categories') }}</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        Dead End
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assessmentCategory/show.blade.php
@extends('layouts.app')

@section('page-title')
    {{ $model->name }}
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentModel.index','Models') }}</li>
        <li class="active">{{ link_to_route('assessmentModel.show', $model->assessmentModel->name, [$model->assessmentModel->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentCategory.show', $model->name, [$model->id]) }}</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="pull-right">
                            <a href="{{ route('assessmentCategory.edit',  [$model->id]) }}">
                                <span class="glyphicon glyphicon-edit"></span>
                            </a>
                        </div>
                        <dl class="dl-horizontal">
                           <dt>Category Name</dt>
                            <dd>{{ $model->name }}</dd>

                            <dt>Description</dt>
                            <dd>{{ $model->description }}</dd>

                            <dt>Image</dt>
                            <dd>{{ $model->image }}</dd>

                            <dt>Model</dt>
                            <dd>
                                <a href="{{ route('assessmentModel.show',  [$model->id]) }}">
                                    {{ $model->assessmentModel->name }}
                                </a>
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1>Sub Categories</h1>
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                <tr>
                                    <th>
                                        Order
                                    </th>
                                    <th colspan="2">
                                        Sub Category
                                    </th>
                                    <th>
                                        Category Weighting
                                    </th>
                                    <th>
                                        Assessment Weighting
                                    </th>
                                    <th>
                                        Ignoreable
                                    </th>
                                    <td align="right">
                                        <a href="{{ route('assessmentSubCategory.create') . '?parent=' . $model->id }}" class="pull-right">
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </a>
                                    </td>
                                </tr>
                                @foreach($model->assessmentSubCategories()->orderBy('display_weight')->get() as $ix)
                                    <tr>
                                        <td>
                                            {{ $ix->display_weight }}
                                        </td>
                                        <td>
                                            <a href="{{ route('assessmentSubCategory.show',  [$ix->id]) }}">
                                                {{ $ix->name }}
                                            </a>
                                        </td>
                                        <td>
                                            {{ $ix->description }}
                                        </td>
                                        <td>
                                            {{ $ix->category_weighting }}
                                        </td>
                                        <td>
                                            {{ $ix->assessment_weighting }}
                                        </td>
                                        <td>
                                            @if($ix->ignoreable)
                                                Yes
                                            @else
                                                No
                                            @endif
                                        </td>
                                        <td width="10px">
                                            <a href="{{ route('assessmentSubCategory.edit',  [$ix->id]) }}">
                                                <span class="glyphicon glyphicon-edit"></span>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection