routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('root');

Auth::routes();

Route::get('/home/{user?}', 'HomeController@index')->name('home');

Route::resource('user','UserController');
Route::resource('assessmentModel','AssessmentModelController');
Route::resource('assessmentCategory','AssessmentCategoryController');
Route::resource('assessmentSubCategory','AssessmentSubCategoryController');
Route::resource('assessmentVariable','AssessmentVariableController');
Route::resource('assessmentVariableValue','AssessmentVariableValueController');
Route::resource('assessmentBenefit','AssessmentBenefitController');

Route::resource('assessmentVariable', 'AssessmentVariableController');
Route::resource('assessmentSubmission', 'AssessmentSubmissionController');

Route::get('/assessmentDump/{assessmentSubmission}', 'AssessmentSubmissionController@dump');

Route::get('methodology/{assessmentModel}','AssessmentModelController@hierarchy')->name('methodology');

Route::get('/submit/{assessmentSubmission}/{assessmentSubCategory}/','AssessmentSubmissionController@submit')->name('submit');
Route::get('/submitBenefits/{assessmentSubmission}','AssessmentSubmissionController@submitBenefits')->name('submitBenefits');

app/AssessmentSubCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Closure;

class AssessmentSubCategory extends Model
{
    protected $fillable = [
        'name',
        'description',
        'image',
        'assessment_category_id',
        'ignoreable',
        'category_weighting',
        'assessment_weighting',
        'display_weight',
    ];

    public function assessmentCategory()
    {
        return $this->belongsTo(AssessmentCategory::class);
    }

    public function assessmentVariables()
    {
        return $this->hasMany(AssessmentVariable::class);
    }

    public static function importFromCSV($source_file, Closure $callback)
    {
        if (!file_exists($source_file)) {
            throw new \Exception("File not found: " . $source_file);
        }

        $row_num = 0;
        $headers = [];
        if (($handle = fopen($source_file, "r")) !== FALSE) {
            while (($row = fgetcsv($handle, 4096, ",")) !== FALSE) {
                $row_num++;
                if ($row_num == 1) {
                    $headers = $row;
                    continue;
                }

                $data = [];
                foreach ($row as $k => $v) {
                    $data[$headers[$k]] = $v;
                }

                try {
                    $assessmentModel = assessmentModel::where('name', $data['model'])->first();

                    $assessmentCategory = AssessmentCategory::where('name', $data['category'])
                        ->where('assessment_model_id', $assessmentModel->id)->first();

                    unset($data['model']);
                    unset($data['category']);

                    $newRow = $assessmentCategory->assessmentSubCategories()->create($data);
                } catch (\Exception $ex) {
                    print "Shit: Died at " . print_r($data, TRUE);
                    throw $ex;
                }
                $callback($newRow);
            }

            fclose($handle);

            // Account for the header
            return ($row_num - 1);
        }
    }
}

app/Http/Controllers/AssessmentSubCategoryController.php
<?php

namespace App\Http\Controllers;

use App\AssessmentCategory;
use App\AssessmentSubCategory;
use Illuminate\Http\Request;

class AssessmentSubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $models = AssessmentSubCategory::simplePaginate();
        return view('assessmentSubCategory.index', compact('models'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if(! $request->get('parent')){
            throw new NotFoundHttpException("Model not found");
        }

        $parent = AssessmentCategory::findOrFail($request->get('parent'));

        return view('assessmentSubCategory.create',compact('parent'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'description' => 'required',
            'display_weight' => 'required',
            'category_weighting' => 'required|numeric',
            'assessment_weighting' => 'required|numeric',
            'assessment_category_id' => 'required|exists:assessment_categories,id'
        ]);

        $data = $request->all();
        $data['ignoreable'] = $request->get('ignoreable') ? 1 : 0;

        $model = AssessmentSubCategory::create( $data);

        return redirect(route('assessmentSubCategory.show', [ $model->id ]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\AssessmentSubCategory  $assessmentSubCategory
     * @return \Illuminate\Http\Response
     */
    public function show(AssessmentSubCategory $assessmentSubCategory)
    {
        $model = $assessmentSubCategory;
        return view('assessmentSubCategory.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\AssessmentSubCategory  $assessmentSubCategory
     * @return \Illuminate\Http\Response
     */
    public function edit(AssessmentSubCategory $assessmentSubCategory)
    {
        $model = $assessmentSubCategory;
        return view('assessmentSubCategory.edit',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AssessmentSubCategory  $assessmentSubCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AssessmentSubCategory $assessmentSubCategory)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'description' => 'required',
            'display_weight' => 'required',
            'category_weighting' => 'required|numeric',
            'assessment_weighting' => 'required|numeric'
        ]);

        $data = $request->all();
        $data['ignoreable'] = $request->get('ignoreable') ? 1 : 0;

        $assessmentSubCategory->fill($data);
        $assessmentSubCategory->save();

        return redirect(route('assessmentSubCategory.show', [ $assessmentSubCategory->id ]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AssessmentSubCategory  $assessmentSubCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy(AssessmentSubCategory $assessmentSubCategory)
    {
        //
    }
}

resources/views/assessmentSubCategory/_form.blade.php
@if($model->id)
    {!! Form::model($model, ['route' => ['assessmentSubCategory.update', $model->id], 'method' => 'put']) !!}
@else
    {!! Form::model($model, ['route' => ['assessmentSubCategory.store']]) !!}
@endif

<div class="form-group {{ $errors->has('name') ? 'has-error' :'' }}">
    {{ Form::label('name') }}
    {{ Form::text('name', $model->name, ['class' => "form-control"]) }}
    {!! $errors->first('name','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('description') ? 'has-error' :'' }}">
    {{ Form::label('description') }}
    {{ Form::text('description', $model->description, ['class' => "form-control"]) }}
    {!! $errors->first('description','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('image') ? 'has-error' :'' }}">
    {{ Form::label('image') }}
    {{ Form::text('image', $model->image, ['class' => "form-control"]) }}
    {!! $errors->first('image','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('display_weight') ? 'has-error' :'' }}">
    {{ Form::label('display_weight') }}
    {{ Form::number('display_weight', $model->display_weight, ['class' => "form-control"]) }}
    {!! $errors->first('display_weight','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('category_weighting') ? 'has-error' :'' }}">
    {{ Form::label('category_weighting') }}
    {{ Form::text('category_weighting', $model->category_weighting, ['class' => "form-control"]) }}
    {!! $errors->first('category_weighting','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('assessment_weighting') ? 'has-error' :'' }}">
    {{ Form::label('assessment_weighting') }}
    {{ Form::text('assessment_weighting', $model->assessment_weighting, ['class' => "form-control"]) }}
    {!! $errors->first('assessment_weighting','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('ignoreable') ? 'has-error' :'' }}">
    {{ Form::label('ignoreable') }}
    {{ Form::checkbox('ignoreable', '1' , $model->ignoreable) }}
    {!! $errors->first('ignoreable','<span class="help-block">:message</span>') !!}
</div>

@if(! $model->id)
    {{Form::hidden('assessment_category_id', $parent->id)}}
@endif

<div class="form-group">
    {{ Form::submit('Save',['class' => 'btn btn-default']) }}
</div>

{!! Form::close() !!}

resources/views/assessmentSubCategory/create.blade.php
@extends('layouts.app')

@section('page-title', 'Create SubCategory')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentModel.index','Models') }}</li>
        <li class="active">{{ link_to_route('assessmentModel.show', $parent->assessmentModel->name, [$parent->assessmentModel->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentCategory.show', $parent->name, [$parent->id]) }}</li>
        <li>Create Sub Category</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @include('assessmentSubCategory._form', [ 'model' => new App\AssessmentSubCategory() ])
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assessmentSubCategory/edit.blade.php
@extends('layouts.app')

@section('page-title', 'Update SubCategory')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentModel.index','Models') }}</li>
        <li class="active">{{ link_to_route('assessmentModel.show', $model->assessmentCategory->assessmentModel->name, [$model->assessmentCategory->assessmentModel->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentCategory.show', $model->assessmentCategory->name, [$model->assessmentCategory->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentSubCategory.show', $model->name, [$model->id]) }}</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @include('assessmentSubCategory._form', compact('assessmentSubCategory'))
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assessmentSubCategory/index.blade.php
@extends('layouts.app')

@section('page-title', 'SubCategories')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentSubCategory.index','SubCategories') }}</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        Dead End
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assessmentSubCategory/show.blade.php
@extends('layouts.app')

@section('page-title')
    {{ $model->name }}
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentModel.index','Models') }}</li>
        <li class="active">{{ link_to_route('assessmentModel.show', $model->assessmentCategory->assessmentModel->name, [$model->assessmentCategory->assessmentModel->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentCategory.show', $model->assessmentCategory->name, [$model->assessmentCategory->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentSubCategory.show', $model->name, [$model->id]) }}</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="pull-right">
                            <a href="{{ route('assessmentSubCategory.edit',  [$model->id]) }}">
                                <span class="glyphicon glyphicon-edit"></span>
                            </a>
                        </div>
                        <dl class="dl-horizontal">
                           <dt>Sub Category Name</dt>
                            <dd>{{ $model->name }}</dd>

                            <dt>Description</dt>
                            <dd>{{ $model->description }}</dd>

                            <dt>Category Weighting</dt>
                            <dd>{{ $model->category_weighting }}</dd>

                            <dt>Assessment Weighting</dt>
                            <dd>{{ $model->assessment_weighting }}</dd>

                            <dt>Ignoreable</dt>
                            <dd>
                                @if($model->ignoreable)
                                    Yes
                                @else
                                    No
                                @endif
                            </dd>

                            <dt>Image</dt>
                            <dd>{{ $model->image }}</dd>

                            <dt>Category</dt>
                            <dd>
                                <a href="{{ route('assessmentCategory.show',  [$model->assessmentCategory->id]) }}">
                                    {{ $model->assessmentCategory->name }}
                                </a>
                            </dd>

                            <dt>Model</dt>
                            <dd>
                                <a href="{{ route('assessmentModel.show',  [$model->assessmentCategory->assessmentModel->id]) }}">
                                    {{ $model->assessmentCategory->assessmentModel->name }}
                                </a>
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1>Variables</h1>
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                <tr>
                                    <th>
                                        Order
                                    </th>
                                    <th colspan="2">
                                        Variable
                                    </th>
                                    <th>
                                        Rank
                                    </th>
                                    <td align="right">
                                        <a href="{{ route('assessmentVariable.create') . '?parent=' . $model->id }}" class="pull-right">
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </a>
                                    </td>
                                </tr>
                                @foreach($model->assessmentVariables()->orderBy('display_weight')->get() as $ix)
                                    <tr>
                                        <td>
                                            {{ $ix->display_weight }}
                                        </td>
                                        <td>
                                            <a href="{{ route('assessmentVariable.show',  [$ix->id]) }}">
                                                {{ $ix->name }}
                                            </a>
                                        </td>
                                        <td>
                                            {{ $ix->description }}
                                        </td>
                                        <td>
                                            {{ $ix->rank }}
                                        </td>
                                        <td width="10px">
                                            <a href="{{ route('assessmentVariable.edit',  [$ix->id]) }}">
                                                <span class="glyphicon glyphicon-edit"></span>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection