routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('root');

Auth::routes();

Route::get('/home/{user?}', 'HomeController@index')->name('home');

Route::resource('user','UserController');
Route::resource('assessmentModel','AssessmentModelController');
Route::resource('assessmentCategory','AssessmentCategoryController');
Route::resource('assessmentSubCategory','AssessmentSubCategoryController');
Route::resource('assessmentVariable','AssessmentVariableController');
Route::resource('assessmentVariableValue','AssessmentVariableValueController');
Route::resource('assessmentBenefit','AssessmentBenefitController');

Route::resource('assessmentVariable', 'AssessmentVariableController');
Route::resource('assessmentSubmission', 'AssessmentSubmissionController');

Route::get('/assessmentDump/{assessmentSubmission}', 'AssessmentSubmissionController@dump');

Route::get('methodology/{assessmentModel}','AssessmentModelController@hierarchy')->name('methodology');

Route::get('/submit/{assessmentSubmission}/{assessmentSubCategory}/','AssessmentSubmissionController@submit')->name('submit');
Route::get('/submitBenefits/{assessmentSubmission}','AssessmentSubmissionController@submitBenefits')->name('submitBenefits');

app/AssessmentVariable.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Closure;

class AssessmentVariable extends Model
{
    protected $fillable = [
        'name',
        'description',
        'image',
        'rank',
        'assessment_sub_category_id',
        'display_weight',
    ];

    public function AssessmentSubCategory()
    {
        return $this->belongsTo(AssessmentSubCategory::class);
    }

    public function AssessmentVariableValues()
    {
        return $this->hasMany(AssessmentVariableValue::class);
    }

    public static function importFromCSV($source_file, Closure $callback)
    {
        if (!file_exists($source_file)) {
            throw new \Exception("File not found: " . $source_file);
        }

        $row_num = 0;
        $headers = [];
        if (($handle = fopen($source_file, "r")) !== FALSE) {
            while (($row = fgetcsv($handle, 4096, ",")) !== FALSE) {
                $row_num++;
                if ($row_num == 1) {
                    $headers = $row;
                    continue;
                }

                $data = [];
                foreach ($row as $k => $v) {
                    $data[$headers[$k]] = $v;
                }

                try {
                    $assessmentModel = assessmentModel::where('name', $data['model'])->first();
                    $assessmentCategory = AssessmentCategory::where('name', $data['category'])
                        ->where('assessment_model_id', $assessmentModel->id)->first();

                    $assessmentSubCategory = AssessmentSubCategory::where('name', $data['subcategory'])
                        ->where('assessment_category_id', $assessmentCategory->id)->first();

                    unset($data['model']);
                    unset($data['category']);
                    unset($data['subcategory']);


                    $newRow = $assessmentSubCategory->assessmentVariables()->create($data);
                } catch (\Exception $ex) {
                    print "Shit: Died at " . print_r($data, TRUE);
                    throw $ex;
                }
                $callback($newRow);
            }

            fclose($handle);

            // Account for the header
            return ($row_num - 1);
        }
    }
}

app/Http/Controllers/AssessmentVariableController.php
<?php

namespace App\Http\Controllers;

use App\AssessmentSubCategory;
use App\AssessmentVariable;
use Illuminate\Http\Request;

class AssessmentVariableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $models = AssessmentVariable::simplePaginate();
        return view('assessmentVariable.index', compact('models'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if(! $request->get('parent')){
            throw new NotFoundHttpException("Model not found");
        }

        $parent = AssessmentSubCategory::findOrFail($request->get('parent'));
        return view('assessmentVariable.create', compact('parent'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'description' => 'required',
            'rank' => 'required|numeric',
            'display_weight' => 'required|numeric',
            'assessment_sub_category_id' => 'required|exists:assessment_sub_categories,id'
        ]);

        $data = $request->all();

        $model = AssessmentVariable::create( $data);

        return redirect(route('assessmentVariable.show', [ $model->id ]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\AssessmentVariable  $assessmentVariable
     * @return \Illuminate\Http\Response
     */
    public function show(AssessmentVariable $assessmentVariable)
    {
        $model = $assessmentVariable;
        return view('assessmentVariable.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\AssessmentVariable  $assessmentVariable
     * @return \Illuminate\Http\Response
     */
    public function edit(AssessmentVariable $assessmentVariable)
    {
        $model = $assessmentVariable;
        return view('assessmentVariable.edit',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AssessmentVariable  $assessmentVariable
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AssessmentVariable $assessmentVariable)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'description' => 'required',
            'rank' => 'required|numeric',
            'display_weight' => 'required|numeric',
        ]);

        $assessmentVariable->fill($request->all());
        $assessmentVariable->save();

        return redirect(route('assessmentVariable.show', [ $assessmentVariable->id ]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AssessmentVariable  $assessmentVariable
     * @return \Illuminate\Http\Response
     */
    public function destroy(AssessmentVariable $assessmentVariable)
    {
        //
    }
}

resources/views/assessmentVariable/_form.blade.php
@if($model->id)
    {!! Form::model($model, ['route' => ['assessmentVariable.update', $model->id], 'method' => 'put']) !!}
@else
    {!! Form::model($model, ['route' => ['assessmentVariable.store']]) !!}
@endif

<div class="form-group {{ $errors->has('name') ? 'has-error' :'' }}">
    {{ Form::label('name') }}
    {{ Form::text('name', $model->name, ['class' => "form-control"]) }}
    {!! $errors->first('name','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('description') ? 'has-error' :'' }}">
    {{ Form::label('description') }}
    {{ Form::text('description', $model->description, ['class' => "form-control"]) }}
    {!! $errors->first('description','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('image') ? 'has-error' :'' }}">
    {{ Form::label('image') }}
    {{ Form::text('image', $model->image, ['class' => "form-control"]) }}
    {!! $errors->first('image','<span class="help-block">:message</span>') !!}
</div>


<div class="form-group {{ $errors->has('display_weight') ? 'has-error' :'' }}">
    {{ Form::label('display_weight') }}
    {{ Form::number('display_weight', $model->display_weight, ['class' => "form-control"]) }}
    {!! $errors->first('display_weight','<span class="help-block">:message</span>') !!}
</div>


<div class="form-group {{ $errors->has('rank') ? 'has-error' :'' }}">
    {{ Form::label('rank') }}
    {{ Form::number('rank', $model->rank, ['class' => "form-control"]) }}
    {!! $errors->first('rank','<span class="help-block">:message</span>') !!}
</div>

@if(! $model->id)
    {{Form::hidden('assessment_sub_category_id', $parent->id)}}
@endif

<div class="form-group">
    {{ Form::submit('Save',['class' => 'btn btn-default']) }}
</div>

{!! Form::close() !!}

resources/views/assessmentVariable/create.blade.php
@extends('layouts.app')

@section('page-title', 'Create Variable')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentModel.index','Models') }}</li>
        <li class="active">{{ link_to_route('assessmentModel.show', $parent->assessmentCategory->assessmentModel->name, [$parent->assessmentCategory->assessmentModel->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentCategory.show', $parent->assessmentCategory->name, [$parent->assessmentCategory->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentSubCategory.show', $parent->name, [$parent->id]) }}</li>
        <li>Create Variabley</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @include('assessmentVariable._form', [ 'model' => new App\AssessmentVariable() ])
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assessmentVariable/edit.blade.php
@extends('layouts.app')

@section('page-title', 'Update Variable')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentModel.index','Models') }}</li>
        <li class="active">{{ link_to_route('assessmentModel.show', $model->assessmentSubCategory->assessmentCategory->assessmentModel->name, [$model->assessmentSubCategory->assessmentCategory->assessmentModel->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentCategory.show', $model->assessmentSubCategory->assessmentCategory->name, [$model->assessmentSubCategory->assessmentCategory->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentSubCategory.show', $model->assessmentSubCategory->name, [$model->assessmentSubCategory->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentVariable.show', $model->name, [$model->id]) }}</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @include('assessmentVariable._form', compact('assessmentVariable'))
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assessmentVariable/index.blade.php
@extends('layouts.app')

@section('page-title', 'SubCategories')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentVariable.index','SubCategories') }}</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        Dead End
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assessmentVariable/show.blade.php
@extends('layouts.app')

@section('page-title')
    {{ $model->name }}
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentModel.index','Models') }}</li>
        <li class="active">{{ link_to_route('assessmentModel.show', $model->assessmentSubCategory->assessmentCategory->assessmentModel->name, [$model->assessmentSubCategory->assessmentCategory->assessmentModel->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentCategory.show', $model->assessmentSubCategory->assessmentCategory->name, [$model->assessmentSubCategory->assessmentCategory->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentSubCategory.show', $model->assessmentSubCategory->name, [$model->assessmentSubCategory->id]) }}</li>
        <li class="active">{{ link_to_route('assessmentVariable.show', $model->name, [$model->id]) }}</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="pull-right">
                            <a href="{{ route('assessmentVariable.edit',  [$model->id]) }}">
                                <span class="glyphicon glyphicon-edit"></span>
                            </a>
                        </div>
                        <dl class="dl-horizontal">
                           <dt>Variable Name</dt>
                            <dd>{{ $model->name }}</dd>

                            <dt>Description</dt>
                            <dd>{{ $model->description }}</dd>

                            <dt>Image</dt>
                            <dd>{{ $model->image }}</dd>

                            <dt>Rank</dt>
                            <dd>{{ $model->rank }}</dd>

                            <dt>Sub Category</dt>
                            <dd>
                                <a href="{{ route('assessmentSubCategory.show',  [$model->assessmentSubCategory->id]) }}">
                                    {{ $model->assessmentSubCategory->name }}
                                </a>
                            </dd>

                            <dt>Category</dt>
                            <dd>
                                <a href="{{ route('assessmentCategory.show',  [$model->assessmentSubCategory->assessmentCategory->id]) }}">
                                    {{ $model->assessmentSubCategory->assessmentCategory->name }}
                                </a>
                            </dd>

                            <dt>Model</dt>
                            <dd>
                                <a href="{{ route('assessmentModel.show',  [$model->assessmentSubCategory->assessmentCategory->assessmentModel->id]) }}">
                                    {{ $model->assessmentSubCategory->assessmentCategory->assessmentModel->name }}
                                </a>
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1>Variable Values</h1>
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                <tr>
                                    <th>
                                        Order
                                    </th>
                                    <th>
                                        Variable
                                    </th>
                                    <th>
                                        Value
                                    </th>
                                    <td align="right">
                                        <a href="{{ route('assessmentVariableValue.create') . '?parent=' . $model->id }}" class="pull-right">
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </a>
                                    </td>
                                </tr>
                                @foreach($model->assessmentVariableValues()->orderBy('display_weight')->get() as $ix)
                                    <tr>
                                        <td>
                                            {{ $ix->display_weight }}
                                        </td>
                                        <td>
                                            <a href="{{ route('assessmentVariableValue.show',  [$ix->id]) }}">
                                                {{ $ix->name }}
                                            </a>
                                        </td>
                                        <td>
                                            {{ $ix->weighting }}
                                        </td>
                                        <td width="10px">
                                            <a href="{{ route('assessmentVariableValue.edit',  [$ix->id]) }}">
                                                <span class="glyphicon glyphicon-edit"></span>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection