routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('root');

Auth::routes();

Route::get('/home/{user?}', 'HomeController@index')->name('home');

Route::resource('user','UserController');
Route::resource('assessmentModel','AssessmentModelController');
Route::resource('assessmentCategory','AssessmentCategoryController');
Route::resource('assessmentSubCategory','AssessmentSubCategoryController');
Route::resource('assessmentVariable','AssessmentVariableController');
Route::resource('assessmentVariableValue','AssessmentVariableValueController');
Route::resource('assessmentBenefit','AssessmentBenefitController');

Route::resource('assessmentVariable', 'AssessmentVariableController');
Route::resource('assessmentSubmission', 'AssessmentSubmissionController');

Route::get('/assessmentDump/{assessmentSubmission}', 'AssessmentSubmissionController@dump');

Route::get('methodology/{assessmentModel}','AssessmentModelController@hierarchy')->name('methodology');

Route::get('/submit/{assessmentSubmission}/{assessmentSubCategory}/','AssessmentSubmissionController@submit')->name('submit');
Route::get('/submitBenefits/{assessmentSubmission}','AssessmentSubmissionController@submitBenefits')->name('submitBenefits');

app/AssessmentModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Closure;

class AssessmentModel extends Model
{
    protected $fillable = [
        'name',
        'description',
        'image',
        'display_weight',
  ];

  public function assessmentCategories()
  {
      return $this->hasMany(AssessmentCategory::class);
  }

  public function assessmentBenefits()
  {
      return $this->hasMany(AssessmentBenefit::class);
  }

  public static function importFromCSV($source_file, Closure $callback)
  {
      if (!file_exists($source_file)) {
          throw new \Exception("File not found: " . $source_file);
      }

      $row_num = 0;
      $headers = [];
      if (($handle = fopen($source_file, "r")) !== FALSE) {
          while (($row = fgetcsv($handle, 4096, ",")) !== FALSE) {
              $row_num++;
              if ($row_num == 1) {
                  $headers = $row;
                  continue;
              }

              $data = [];
              foreach ($row as $k => $v) {
                  $data[$headers[$k]] = $v;
              }

              $newRow = AssessmentModel::create($data);
              $callback($newRow);
          }

          fclose($handle);

          // Account for the header
          return ($row_num - 1);
      }
  }
}

app/Http/Controllers/AssessmentModelController.php
<?php

namespace App\Http\Controllers;

use App\AssessmentModel;
use Illuminate\Http\Request;

class AssessmentModelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $models = AssessmentModel::simplePaginate();
        return view('assessmentModel.index', compact('models'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('assessmentModel.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'description' => 'required',
            'image' => 'required|max:255',
        ]);

        $data = $request->all();

        $model = AssessmentModel::create( $data);

        return redirect(route('assessmentModel.show', [ $model->id ]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\AssessmentModel  $assessmentModel
     * @return \Illuminate\Http\Response
     */
    public function show(AssessmentModel $assessmentModel)
    {
        $model = $assessmentModel;
        return view('assessmentModel.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\AssessmentModel  $assessmentModel
     * @return \Illuminate\Http\Response
     */
    public function edit(AssessmentModel $assessmentModel)
    {
        $model = $assessmentModel;
        return view('assessmentModel.edit',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AssessmentModel  $assessmentModel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AssessmentModel $assessmentModel)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'description' => 'required',
            'image' => 'required|max:255',
        ]);

        $assessmentModel->fill($request->all());
        $assessmentModel->save();

        return redirect(route('assessmentModel.show', [ $assessmentModel->id ]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AssessmentModel  $assessmentModel
     * @return \Illuminate\Http\Response
     */
    public function destroy(AssessmentModel $assessmentModel)
    {
        //
    }

    public function hierarchy(AssessmentModel $assessmentModel) {
        $model = $assessmentModel;
        return view('assessmentModel.hierarchy', compact('model'));
    }
}

resources/views/assessmentModel/_form.blade.php
@if($model->id)
    {!! Form::model($model, ['route' => ['assessmentModel.update', $model->id], 'method' => 'put']) !!}
@else
    {!! Form::model($model, ['route' => ['assessmentModel.store']]) !!}
@endif

<div class="form-group {{ $errors->has('name') ? 'has-error' :'' }}">
    {{ Form::label('name') }}
    {{ Form::text('name', $model->name, ['class' => "form-control"]) }}
    {!! $errors->first('name','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('description') ? 'has-error' :'' }}">
    {{ Form::label('description') }}
    {{ Form::text('description', $model->description, ['class' => "form-control"]) }}
    {!! $errors->first('description','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('image') ? 'has-error' :'' }}">
    {{ Form::label('image') }}
    {{ Form::text('image', $model->image, ['class' => "form-control"]) }}
    {!! $errors->first('image','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has('display_weight') ? 'has-error' :'' }}">
    {{ Form::label('display_weight') }}
    {{ Form::number('display_weight', $model->display_weight, ['class' => "form-control"]) }}
    {!! $errors->first('display_weight','<span class="help-block">:message</span>') !!}
</div>

<div class="form-group">
    {{ Form::submit('Save',['class' => 'btn btn-default']) }}
</div>

{!! Form::close() !!}

resources/views/assessmentModel/create.blade.php
@extends('layouts.app')

@section('page-title', 'Create Model')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentModel.index','Models') }}</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @include('assessmentModel._form', [ 'model' => new App\AssessmentModel() ])
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assessmentModel/edit.blade.php
@extends('layouts.app')

@section('page-title', 'Update Model')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentModel.index','Models') }}</li>
        <li class="active">{{ link_to_route('assessmentModel.show', $model->name, [$model->id]) }}</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @include('assessmentModel._form', compact('assessmentModel'))
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assessmentModel/hierarchy.blade.php
@extends('layouts.app')

@section('page-title')
    {{ $model->name }}
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2>
                            Model: {{ $model->name }}
                        </h2>
                        <p>
                            <b>Hierarchy:</b> Category > Subcategory > Variable > Variable Value
                        </p>
                        <p>
                            Subcategories are weighted relevant to other subcategories within each category as well as
                            weighted globally relevant to all other subcategories.
                            Variables are ranked according to one another and variable values have vulnerability
                            weightings, listed in order of severity.
                        </p>
                        <hr>
                        <p>
                            <b>Subcategory Risk</b> = ( R<sub>var1</sub> * W<sub>var1</sub> * KW<sub>var1</sub> ) + ( R<sub>var2</sub> * W<sub>var2</sub> * KW<sub>var2</sub>... )
                            <br>where<br>
                            R = Variable Rank<br>
                            W = Variable Value Vulnerability Weighting<br>
                            KW = Knowledge Weighting<br>
                        </p>
                        <hr>
                        <p>
                            <b>Knowledge Weightings (KW) are user input values:</b>
                        </p>
                        <table class="table">
                            <tr>
                                <td width="10%">1</td>
                                <td>Certain</td>
                            </tr>
                            <tr>
                                <td>1.5</td>
                                <td>Somewhat Certain</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>Uncertain</td>
                            </tr>
                        </table>
                        <p>
                            Knowledge weightings are defaulted to 1 ("certain") in the "very familiar / familiar" model with no options to adjust certainty levels mid-assessment. Knowledge weightings are defaulted to 1.5 ("somewhat certain") in the "somewhat familiar / unfamiliar" model with options to adjust the certainty at the variable level throughout the assessment.
                        </p>
                        <hr>
                        <p>
                            Risk Levels (RL) are the same for subcategories, categories, and the total risk rating.
                        </p>
                        <table class="table">
                            <tr>
                                <td width="10%">5</td>
                                <td>Very High</td>
                            </tr>
                            <tr>
                                <td>4</td>
                                <td>High</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>Moderate</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>Low</td>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>Very Low</td>
                            </tr>
                        </table>
                        <hr>
                        <p>
                            <b>Category Risk</b> = ( RL<sub>subcat1</sub> * CW<sub>subcat1</sub> ) + ( RL<sub>subcat2</sub> * CW<sub>subcat2</sub>... )
                            <br>where
                            <b>RL</b> = Subcategory Risk Level (scale of 1 - 5)<br>
                            <b>CW</b> = The subcategory weighting within the category (Internal Category Weighting)
                        </p>
                        <hr>
                        <p>
                            <b>Total Site Risk</b> = ( RL<sub>subcat1</sub> * GW<sub>subcat1</sub> ) + ( RL<sub>subcat2</sub> * GW<sub>subcat2</sub>...)
                            <br>where
                            <br><b>RL</b> = Subcategory Risk Level (scale of 1 - 5)
                            <br><b>GW</b> = Global Subcategory Weighting in relation to all other subcategories
                            regardless of
                            category
                        </p>
                        <hr>
                        <p>
                            Benefits are calculated independently
                        </p>
                        <table class="table">
                            <tr>
                                <td width="10%">
                                    Very High
                                </td>
                                <td>
                                    maximum value >= 7 & count > 1
                                </td>
                            </tr>
                            <tr>
                                <td>
                                     High
                                </td>
                                <td>
                                    maximum value >= 7
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Moderate
                                </td>
                                <td>
                                    4 <= maximum value <= 6
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Low
                                </td>
                                <td>
                                    2 <= maximum value <= 3
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Very Low
                                </td>
                                <td>
                                    maximum value <= 1
                                </td>
                            </tr>
                        </table>
                        <hr>
                        <p>
                            Subcategories defaulted to "Not Applicable", visible in grey when you start a new
                            assessment, are flagged as ignorable when no data is entered. This means their risk ratings
                            are not included in the category and total risk calculations.
                        </p>
                        <p>
                            Subcategories with a "Very Low Risk", equating to a Risk Value of 1, are not multiplied by
                            the CW or GW in the category and total risk calculations.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        @foreach($model->assessmentCategories()->orderBy('display_weight')->get() as $category)
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Category {{ $category->name }}
                        </div>
                        <div class="panel-body">
                            @foreach($category->assessmentSubCategories()->orderBy('display_weight')->get() as $subCategory)
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                Subcategory: {{ $subCategory->name }}
                                            </div>
                                            <div class="panel-body">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <table>
                                                            <tr>
                                                                <td>
                                                                    <b>Internal Subcategory
                                                                        Weighting:</b> {{ $subCategory->category_weighting }}
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>
                                                                    <b>Global Subcategory
                                                                        Weighting:</b> {{ $subCategory->assessment_weighting }}
                                                                </td>
                                                            </tr>
                                                        </table>
                                                        <br>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="panel panel-default">
                                                            <div class="panel-body">
                                                                <table class="table">
                                                                    <tr>
                                                                        <th>Variable</th>
                                                                        <th>Rank</th>
                                                                        <th>Values</th>
                                                                    </tr>
                                                                    @foreach($subCategory->assessmentVariables()->orderBy('display_weight')->get() as $variable)
                                                                        <tr>
                                                                            <td>
                                                                                {{ $variable->name }}
                                                                            </td>
                                                                            <td>
                                                                                {{ $variable->rank }}
                                                                            </td>
                                                                            <td width="90%">
                                                                                <table class="table" width="100%">
                                                                                    @foreach($variable->assessmentVariableValues()->orderBy('display_weight')->get() as $value)
                                                                                        <tr>
                                                                                            <td>
                                                                                                {{ $value->name }}
                                                                                            </td>
                                                                                            <td width="5%">
                                                                                                {{ $value->weighting }}
                                                                                            </td>
                                                                                        </tr>
                                                                                    @endforeach
                                                                                </table>
                                                                            </td>
                                                                        </tr>
                                                                    @endforeach
                                                                </table>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/assessmentModel/show.blade.php
@extends('layouts.app')

@section('page-title')
    {{ $model->name }}
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>{{ link_to_route('home','Home') }}</li>
        <li>{{ link_to_route('assessmentModel.index','Models') }}</li>
        <li class="active">{{ link_to_route('assessmentModel.show', $model->name, [$model->id]) }}</li>
    </ol>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="pull-right">
                            <a href="{{ route('assessmentModel.edit',  [$model->id]) }}">
                                <span class="glyphicon glyphicon-edit"></span>
                            </a>
                        </div>
                        <dl class="dl-horizontal">
                            <dt>Model Name</dt>
                            <dd>{{ $model->name }}</dd>

                            <dt>Description</dt>
                            <dd>{{ $model->description }}</dd>

                            <dt>Image</dt>
                            <dd>{{ $model->image }}</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1>Categories</h1>
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                <tr>
                                    <th>
                                        Order
                                    </th>
                                    <th colspan="2">
                                        Category
                                    </th>
                                    <td align="right">
                                        <a href="{{ route('assessmentCategory.create' )  . '?parent=' . $model->id  }}" class="pull-right">
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </a>
                                    </td>
                                </tr>
                                @foreach($model->assessmentCategories()->orderBy('display_weight')->get() as $ix)
                                    <tr>
                                        <td>
                                            {{ $ix->display_weight }}
                                        </td>
                                        <td>
                                            <a href="{{ route('assessmentCategory.show',  [$ix->id]) }}">
                                                {{ $ix->name }}
                                            </a>
                                        </td>
                                        <td>
                                            {{ $ix->description }}
                                        </td>
                                        <td width="10px">
                                            <a href="{{ route('assessmentCategory.edit',  [$ix->id]) }}">
                                                <span class="glyphicon glyphicon-edit"></span>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1>Benefits</h1>
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                <tr>
                                    <th>
                                        Order
                                    </th>
                                    <th colspan="2">
                                        Benefit
                                    </th>
                                    <th>
                                        Maximum Value
                                    </th>
                                    <td align="right">
                                        <a href="{{ route('assessmentBenefit.create' )  . '?parent=' . $model->id  }}" class="pull-right">
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </a>
                                    </td>
                                </tr>
                                @foreach($model->assessmentBenefits()->orderBy('display_weight')->get() as $ix)
                                    <tr>
                                        <td>
                                            {{ $ix->display_weight }}
                                        </td>
                                        <td>
                                            <a href="{{ route('assessmentBenefit.show',  [$ix->id]) }}">
                                                {{ $ix->name }}
                                            </a>
                                        </td>
                                        <td>
                                            {{ $ix->description }}
                                        </td>
                                        <td>
                                            {{ $ix->maximum_value }}
                                        </td>
                                        <td width="10px">
                                            <a href="{{ route('assessmentBenefit.edit',  [$ix->id]) }}">
                                                <span class="glyphicon glyphicon-edit"></span>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection